#!/bin/sh
set -eu

POSTGRES_USER="${LEGISLAGD_POSTGRES_USER:-legislagd}"
POSTGRES_DB="${LEGISLAGD_POSTGRES_DB:-legislagd}"
PLENARIO_DB_NAME="${PLENARIO_DB_NAME:-plenario_core}"
PLENARIO_DB_USER="${PLENARIO_DB_USER:-plenario}"
PLENARIO_DB_PASSWORD="${PLENARIO_DB_PASSWORD:-plenario_dev_password}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${PLENARIO_DB_USER}') THEN
    CREATE ROLE ${PLENARIO_DB_USER} LOGIN PASSWORD '${PLENARIO_DB_PASSWORD}';
  ELSE
    ALTER ROLE ${PLENARIO_DB_USER} WITH LOGIN PASSWORD '${PLENARIO_DB_PASSWORD}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${PLENARIO_DB_NAME} OWNER ${PLENARIO_DB_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${PLENARIO_DB_NAME}')\gexec
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$PLENARIO_DB_NAME" <<-EOSQL
GRANT ALL PRIVILEGES ON DATABASE ${PLENARIO_DB_NAME} TO ${PLENARIO_DB_USER};
GRANT ALL PRIVILEGES ON SCHEMA public TO ${PLENARIO_DB_USER};
EOSQL
