name: Funcionalidade
description: Solicitar melhoria
title: "[feat]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: necessidade
    attributes:
      label: Necessidade
    validations:
      required: true
